version: '3'
services:
  database:
    image: go_db
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    image: go_web
    container_name: web
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8081"

volumes:
  pgdata: {}